In [1]:
import numpy as np

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.patches import Circle

In [2]:
#output settings
np.set_printoptions(precision=2)
%matplotlib qt

In [3]:
#create the grid

#number of grid points
Nq = 100
Nth = 100
Nph = 100

#radius of the star
Rs = 1.

#linear grid in each dimension for compact spherical coordinates
Q = np.linspace(Rs, 0, Nq)
TH = np.linspace(0., np.pi, Nth)
PH = np.linspace(0., 2*np.pi, Nph)

#define the step sizes
dq, dth, dph = Q[1]-Q[0], TH[1]-TH[0], PH[1]-PH[0]

#3d meshgrid
# q, th, ph = np.meshgrid(Q, TH, PH, indexing='ij') 

#2d meshgrid
q, th = np.meshgrid(Q, TH, indexing='ij')

#transformation to normal spherical coordindates
R, r = Rs**2/Q, Rs**2/q

#transformation to cartesian coordinates
X, Y, Z = R*np.sin(TH)*np.cos(PH), R*np.sin(TH)*np.sin(PH), R*np.cos(TH)
# x, y, z = r*np.sin(th)*np.cos(ph), r*np.sin(th)*np.sin(ph), r*np.cos(th)
x, z = r*np.sin(th), r*np.cos(th)


In [4]:
#define the dipole magnetic field
Bq = -2*np.cos(th)*q**3/Rs**6
Bth = -np.sin(th)*q**3/Rs**6

Pdip = np.sin(th)**2/r

In [5]:
#the alpha function (in this case alpha=sin(theta)/r**(1/2))

#analytical value
alpha_an = np.sin(th)/r**(0.5)

#initialise matrix
alpha = np.zeros((Nq, Nth))
#impose boundary conditions at stellar surface i=0
for j in range(0, Nth):
    

    alpha[0, j] = np.sin(TH[j])*Rs**(-0.5)

#calculate alpha for all other grid points
for i in range(0, Nq-1):
    for j in range(0, Nth-1):
        

        alpha[i+1,j] = alpha[i,j] + Bth[i,j]*dq/Bq[i,j]/dth/Q[i]*(alpha[i,j+1] - alpha[i,j])



In [6]:
fig = plt.figure()
ax = fig.add_subplot(111)  
# ax.contour(x, z, alpha)
ax.contour(x, z, alpha_an, cmap=cm.inferno, levels=40)
ax.contour(x, z, Pdip, levels=40, ls='--')
# ax.plot(alpha)
ax.set_xlim(0., 5.)
ax.set_ylim(-2.5, 2.5)

ax.set_xlabel('x')
ax.set_ylabel('z')
ax.set_aspect('equal')

ax.add_patch(Circle((0.,0.), Rs, color='b', zorder=-1))

In [7]:
print(alpha)

[[ 0.00e+00  3.17e-02  6.34e-02 ...  6.34e-02  3.17e-02  1.22e-16]
 [ 0.00e+00  3.16e-02  6.31e-02 ...  6.31e-02  3.16e-02  0.00e+00]
 [ 0.00e+00  3.14e-02  6.28e-02 ...  6.28e-02  3.14e-02  0.00e+00]
 ...
 [ 0.00e+00  4.67e+47 -9.27e+50 ...  9.57e-03  4.79e-03  0.00e+00]
 [ 0.00e+00  2.32e+50 -4.61e+53 ...  7.17e-03  3.59e-03  0.00e+00]
 [ 0.00e+00  2.31e+53 -4.58e+56 ...  3.59e-03  1.79e-03  0.00e+00]]


In [8]:
Pdip

array([[0.00e+00, 1.01e-03, 4.02e-03, ..., 4.02e-03, 1.01e-03, 1.50e-32],
       [0.00e+00, 9.96e-04, 3.98e-03, ..., 3.98e-03, 9.96e-04, 1.48e-32],
       [0.00e+00, 9.86e-04, 3.94e-03, ..., 3.94e-03, 9.86e-04, 1.47e-32],
       ...,
       [0.00e+00, 2.03e-05, 8.13e-05, ..., 8.13e-05, 2.03e-05, 3.03e-34],
       [0.00e+00, 1.02e-05, 4.06e-05, ..., 4.06e-05, 1.02e-05, 1.51e-34],
       [0.00e+00, 0.00e+00, 0.00e+00, ..., 0.00e+00, 0.00e+00, 0.00e+00]])